switch minimap to sockets

diff --git a/dot_sh/executable_MinimapServerTest b/dot_sh/executable_MinimapServerTest
--- a/dot_sh/executable_MinimapServerTest
+++ b/dot_sh/executable_MinimapServerTest
@@ -14,5 +14,5 @@ function request {
     echo "cursor 23"
     echo "preview"
 }
-request | nc -U $socket
+request | nc -vU "$socket" || (echo "failed to connect"; exit)
 cat <&$fd
